name: ext_video_player
description: Flutter plugin for displaying inline  with other Flutter
  widgets on Android and iOS. This plugin also supports playing youtube videos & RTMP Streams
version: 0.0.6
homepage: https://github.com/ponnamkarthik/ext_video_player

flutter:
  plugin:
    platforms:
      android:
        package: ext.videoplayer
        pluginClass: ExtVideoPlayerPlugin
      ios:
        pluginClass: FLTExtVideoPlayerPlugin
      web:
        default_package: video_player_web

dependencies:
  meta: "^1.0.5"
  video_player_platform_interface: ^2.2.0

  # The design on https://flutter.dev/go/federated-plugins was to leave
  # this constraint as "any". We cannot do it right now as it fails pub publish
  # validation, so we set a ^ constraint.
  # TODO(amirh): Revisit this (either update this part in the  design or the pub tool).
  # https://github.com/flutter/flutter/issues/46264
  video_player_web: '>=0.1.4 <2.0.0'
  
  flutter:
    sdk: flutter
  
  http: ^0.13.4
  youtube_explode_dart: ^1.10.9+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0
  pigeon: 0.1.7

environment:
  sdk: '>=2.10.0 <3.0.0'
  flutter: ">=1.12.13+hotfix.5 <2.0.0"
